name: Java Build with Gradle
description: Checkout, Pull Jdk 17, Setup Gradle, Test and Assemble, Submit Dependency Graph

outputs:
  specmatic-version:
    description: "The version of Specmatic that was used to run the tests"
    value: ${{ steps.specmatic-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0

    - name: Test and assemble
      run: ./gradlew check assemble

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
