name: Java Build with Gradle
description: Checkout, Pull Jdk 17, Setup Gradle, Test and Assemble, Submit Dependency Graph

inputs:
  gradle-extra-args:
    description: "Extra arguments to pass to the gradle command"
    required: false
    default: ""

  version-properties-file:
    description: "The file containing the version property"
    required: false
    default: "gradle.properties"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0

    - name: Test and assemble
      run: ./gradlew check assemble ${{ inputs.gradle-extra-args }}
      shell: bash

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0

    - name: Verify version exists in ${{ inputs.version-properties-file }}
      run: grep '^\s*version\s*=' ${{ inputs.version-properties-file }}
      shell: bash

    - name: 'Upload Gradle Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: Gradle Build Artifacts
        path: |
          build/
          */build/
        retention-days: 5
