name: Java Build with Gradle
description: Checkout, Pull Jdk 17, Setup Gradle, Test and Assemble, Submit Dependency Graph

inputs:
  gradle-extra-args:
    description: "Extra arguments to pass to the gradle command"
    required: false
    default: ""

  gradle-extra-env-file:
    description: "File containing any extra environments to set for the gradle task"
    required: false
    default: ""

  pre-gradle-command:
    description: "The command to run before the gradle command"
    required: false
    default: "echo 'No pre-gradle command specified'"

  java-version:
    description: "The Java version to use"
    required: false
    default: "17"

  java-distribution:
    description: "The Java distribution to use"
    required: false
    default: "temurin"

runs:
  using: "composite"
  steps:
    - uses: znsio/specmatic-github-workflows/action-base-setup@main
      with:
        java-version: ${{ inputs.java-version }}
        java-distribution: ${{ inputs.java-distribution }}

    - name: Test and assemble
      run: |
        if [ -f "${{ inputs.gradle-extra-env-file }}" ]; then
          echo "Sourcing ${{ inputs.gradle-extra-env-file }}"
          source "${{ inputs.gradle-extra-env-file }}"
        fi
        ${{ inputs.pre-gradle-command }}
        ./gradlew check assemble ${{ inputs.gradle-extra-args }}
      shell: bash

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0

    - name: 'Upload Gradle Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: Gradle Build Artifacts
        path: |
          build/reports
          */build/reports
          build/jacoco
          */build/jacoco
        retention-days: 5
