name: Java Build with Gradle
description: Checkout, Pull Jdk 17, Setup Gradle, Test and Assemble, Submit Dependency Graph

inputs:
  gradle-extra-args:
    description: "Extra arguments to pass to the gradle command"
    required: false
    default: ""

  gradle-extra-env-file:
    description: "File containing any extra environments to set for the gradle task"
    required: false
    default: ""

  pre-gradle-command:
    description: "The command to run before the gradle command"
    required: false
    default: "echo 'No pre-gradle command specified'"

  java-version:
    description: "The Java version to use"
    required: false
    default: "17"

  java-distribution:
    description: "The Java distribution to use"
    required: false
    default: "temurin"
  github-token-for-pr-comment:
    description: "GitHub token for posting comments on pull requests"
    required: false

runs:
  using: "composite"
  steps:
    - uses: specmatic/specmatic-github-workflows/action-base-setup@main
      with:
        java-version: ${{ inputs.java-version }}
        java-distribution: ${{ inputs.java-distribution }}

    - name: Test and assemble (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if [ -f "${{ inputs.gradle-extra-env-file }}" ]; then
          echo "Sourcing ${{ inputs.gradle-extra-env-file }}"
          source "${{ inputs.gradle-extra-env-file }}"
        fi
        ${{ inputs.pre-gradle-command }}
        ./gradlew check assemble ${{ inputs.gradle-extra-args }}

    - name: Test and assemble (MacOS/Windows)
      if: runner.os != 'Linux'
      shell: bash
      run: |
        if [ -f "${{ inputs.gradle-extra-env-file }}" ]; then
          echo "Sourcing ${{ inputs.gradle-extra-env-file }}"
          source "${{ inputs.gradle-extra-env-file }}"
        fi
        ${{ inputs.pre-gradle-command }}
        ./gradlew test assemble ${{ inputs.gradle-extra-args }}

    - name: Setup .NET Core # Required to execute ReportGenerator
      if: matrix.os == 'ubuntu-latest'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        dotnet-quality: 'ga'

    - name: ReportGenerator
      if: matrix.os == 'ubuntu-latest'
      uses: danielpalme/ReportGenerator-GitHub-Action@v5
      with:
        reports: build/reports/jacoco/*/*.xml;**/build/reports/jacoco/*/*.xml
        targetdir: coveragereport
        reporttypes: Html;MarkdownSummaryGithub;MarkdownAssembliesSummary

    - name: Add coverage to build summary
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0

    - name: 'Upload Gradle Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: Gradle Build Artifacts (${{ runner.os }})
        path: |
          build/reports
          */build/reports
          build/jacoco
          */build/jacoco
        retention-days: 5
