name: Java Build with Gradle
description: Checkout, Pull Jdk 17, Setup Gradle, Test and Assemble, Submit Dependency Graph

inputs:
  gradle-extra-args:
    description: "Extra arguments to pass to the gradle command"
    required: false
    default: ""

  gradle-extra-env-file:
    description: "File containing any extra environments to set for the gradle task"
    required: false
    default: ""

  pre-gradle-command:
    description: "The command to run before the gradle command"
    required: false
    default: "echo 'No pre-gradle command specified'"

  java-version:
    description: "The Java version to use"
    required: false
    default: "17"

  java-distribution:
    description: "The Java distribution to use"
    required: false
    default: "temurin"

  github-token-for-pr-comment:
    description: "GitHub token for posting comments on pull requests"
    required: false

  reportgenerator-extra-reports:
    description: "Additional report files to include in ReportGenerator (semicolon-separated)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: specmatic/specmatic-github-workflows/action-base-setup@main
      with:
        java-version: ${{ inputs.java-version }}
        java-distribution: ${{ inputs.java-distribution }}

    - name: Test and assemble (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if [ -f "${{ inputs.gradle-extra-env-file }}" ]; then
          echo "Sourcing ${{ inputs.gradle-extra-env-file }}"
          source "${{ inputs.gradle-extra-env-file }}"
        fi
        ${{ inputs.pre-gradle-command }}
        ./gradlew check assemble ${{ inputs.gradle-extra-args }}

    - name: Test and assemble (MacOS/Windows)
      if: runner.os != 'Linux'
      shell: bash
      run: |
        if [ -f "${{ inputs.gradle-extra-env-file }}" ]; then
          echo "Sourcing ${{ inputs.gradle-extra-env-file }}"
          source "${{ inputs.gradle-extra-env-file }}"
        fi
        ${{ inputs.pre-gradle-command }}
        ./gradlew test assemble ${{ inputs.gradle-extra-args }}

    - name: Setup .NET Core # Required to execute ReportGenerator
      if: runner.os == 'Linux'
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.x
        dotnet-quality: 'ga'

    - name: ReportGenerator
      if: runner.os == 'Linux'
      uses: danielpalme/ReportGenerator-GitHub-Action@v5
      with:
        reports: build/reports/jacoco/*/*.xml;**/build/reports/jacoco/*/*.xml${{ inputs.reportgenerator-extra-reports != '' && format(';{0}', inputs.reportgenerator-extra-reports) || '' }}
        targetdir: coveragereport
        reporttypes: Html;MarkdownSummaryGithub;MarkdownAssembliesSummary

    - name: Add coverage to build summary
      if: runner.os == 'Linux'
      shell: bash
      run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

    - name: Add coverage comment to PR (linux only)
      if: runner.os == 'Linux' && inputs.github-token-for-pr-comment != '' && github.event_name == 'pull_request'
      run: gh pr comment $PR_NUMBER --edit-last --create-if-none --body-file coveragereport/Summary.md || true
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token-for-pr-comment }}
        PR_NUMBER: ${{ github.event.number }}

    - name: Generate and submit dependency graph
      if: github.event_name != 'pull_request'
      uses: gradle/actions/dependency-submission@v5

    - name: 'Upload Gradle Artifact'
      uses: actions/upload-artifact@v6
      with:
        name: Gradle Build Artifacts (${{ runner.os }})
        path: |
          build/reports
          */build/reports
          build/jacoco
          */build/jacoco
        retention-days: 5
