name: Gradle post build
description: Execute any gradle targets after a gradle assembly is built


inputs:
  gradle-extra-args:
    description: "Extra arguments to pass to the gradle command"
    required: true
    default: "--please-provide-gradle-extra-args"

  gradle-extra-env-file:
    description: "File containing any extra environments to set for the gradle task"
    required: false
    default: ""

  pre-gradle-command:
    description: "The command to run before the gradle command"
    required: false
    default: "echo 'No pre-gradle command specified'"

  download-action-workflow:
    description: "The workflow action name/path to download the artifacts"
    required: false
    default: gradle.yml


  download-artifact-github-token:
    description: "The GitHub token to use for downloading artifacts"
    required: true

  enable-docker-buildx:
    description: "Enable Docker Buildx"
    required: false
    default: "false"

  java-version:
    description: "The Java version to use"
    required: false
    default: "17"

  java-distribution:
    description: "The Java distribution to use"
    required: false
    default: "temurin"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: "${{ inputs.java-version }}"
        distribution: "${{ inputs.java-distribution }}"

    - name: Set up QEMU
      if: inputs.enable-docker-buildx == 'true'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: inputs.enable-docker-buildx == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0

    - name: Download Gradle Artifacts
      uses: dawidd6/action-download-artifact@v9
      with:
        workflow: ${{ inputs.download-action-workflow }}
        allow_forks: false
        github_token: ${{ inputs.download-artifact-github-token }}

    - name: Download semver cli
      run: |
        wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x /usr/local/bin/semver
      shell: bash

    - name: Execute gradle with extra args
      run: |
        if [ -f ${{ inputs.gradle-extra-env-file }} ]; then
          echo "Sourcing ${{ inputs.gradle-extra-env-file }}"
          source ${{ inputs.gradle-extra-env-file }}
        fi
        ${{ inputs.pre-gradle-command }}
        ./gradlew ${{ inputs.gradle-extra-args }}
      shell: bash
