name: Base setup for gradle and java
description: Checkout, Pull Jdk 17, Setup Gradle

inputs:
  java-version:
    description: "The Java version to use"
    required: false
    default: "17"

  java-distribution:
    description: "The Java distribution to use"
    required: false
    default: "temurin"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: "${{ inputs.java-version }}"
        distribution: "${{ inputs.java-distribution }}"

    - name: Download semver cli
      run: |
        wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x /usr/local/bin/semver
      shell: bash

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
